name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Escolha a versão do Python, ex: '3.9'

      # 3. Instala as dependências listadas no arquivo requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Delete all files in a directory from S3
        run: |
            aws s3 rm s3://iam-users-controller/some-directory/ --recursive
    
      - name: Zip files
        run: |
            zip -r deploy.zip . -x ".git/*"

      - name: Sync zipped file to S3
        run: |
            aws s3 cp deploy.zip s3://iam-users-controller/
